<a href="https://colab.research.google.com/github/22cs044Shruti/C-/blob/main/XOR_MultiLayer_perceptron_Pract_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

In [ ]:
input_xor = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
label_xor = np.array([[0], [1], [1], [0]], dtype=np.float32)

In [ ]:
model = Sequential([Dense(10, input_shape=(2,), activation='relu')])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(input_xor, label_xor, epochs=275)

Epoch 1/275


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 586ms/step - accuracy: 0.5000 - loss: 8.8595
Epoch 2/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.2500 - loss: 10.5786
Epoch 3/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.2500 - loss: 10.2305
Epoch 4/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 8.8352
Epoch 5/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 8.8269
Epoch 6/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 8.8185
Epoch 7/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 8.8108
Epoch 8/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 8.8031
Epoch 9/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 8.7953
Epoch 10/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 8.7874
Epoch 11/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 8.7794
Epoch 12/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 8.771

In [ ]:
model.evaluate(input_xor,label_xor)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - accuracy: 0.7500 - loss: 1.7269


[1.7269394397735596, 0.75]

In [ ]:
input_test = np.array([[1,1],[0,1],[0,0],[1,0]])

In [ ]:
model.predict(input_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step


array([[0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       , 0.       ],
       [0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       , 0.       ],
       [0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       , 0.       ],
       [0.       , 0.3742138, 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       , 0.       ]], dtype=float32)

In [ ]:
model_multilayer = Sequential([
    Dense(10, input_shape=(2,), activation='relu'),
    Dense(10, activation='relu'),
    Dense(10, activation='relu'),
    Dense(1, activation='sigmoid')
])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model_multilayer.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model_multilayer.fit(input_xor, label_xor, epochs=275)

Epoch 1/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.5000 - loss: 0.6925
Epoch 2/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.2500 - loss: 0.6916
Epoch 3/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 0.6908
Epoch 4/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.6899
Epoch 5/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 0.6890
Epoch 6/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.6882
Epoch 7/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.6873
Epoch 8/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6864
Epoch 9/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6856
Epoch 10/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6847
Epoch 11/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.6839
Epoch 12/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.7500 - loss

In [ ]:
model.evaluate(input_xor,label_xor)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7500 - loss: 1.7269


[1.7269394397735596, 0.75]

In [ ]:
model_multilayer.predict(input_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step


array([[0.38861176],
       [0.862284  ],
       [0.38861176],
       [0.9772983 ]], dtype=float32)

In [ ]:
model_multilayer_sigmoid = Sequential([
    Dense(10, input_shape=(2,), activation='sigmoid'),
    Dense(10, activation='sigmoid'),
    Dense(10, activation='sigmoid'),
    Dense(1, activation='sigmoid')
])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model_multilayer_sigmoid.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model_multilayer_sigmoid.fit(input_xor, label_xor, epochs=275)

Epoch 1/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.5000 - loss: 0.7099
Epoch 2/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5000 - loss: 0.7088
Epoch 3/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.7078
Epoch 4/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7069
Epoch 5/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.7060
Epoch 6/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.7051
Epoch 7/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.7042
Epoch 8/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5000 - loss: 0.7034
Epoch 9/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 0.7026
Epoch 10/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.7018
Epoch 11/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.7011
Epoch 12/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss

In [ ]:
model_multilayer_sigmoid.evaluate(input_test,label_xor)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 247ms/step - accuracy: 0.5000 - loss: 0.6935


[0.6934965252876282, 0.5]

In [ ]:
model_multilayer_sigmoid.predict(input_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step


array([[0.4995838 ],
       [0.4992666 ],
       [0.50017977],
       [0.50056005]], dtype=float32)

In [ ]:
model_multilayer_tanh = Sequential([
    Dense(10, input_shape=(2,), activation='tanh'),
    Dense(10, activation='tanh'),
    Dense(10, activation='tanh'),
    Dense(1, activation='sigmoid')
])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model_multilayer_tanh.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model_multilayer_tanh.fit(input_xor, label_xor, epochs=275)

Epoch 1/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.5000 - loss: 0.6830
Epoch 2/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.2500 - loss: 0.6812
Epoch 3/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.2500 - loss: 0.6794
Epoch 4/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.2500 - loss: 0.6777
Epoch 5/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.2500 - loss: 0.6760
Epoch 6/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5000 - loss: 0.6743
Epoch 7/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5000 - loss: 0.6727
Epoch 8/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.6710
Epoch 9/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6694
Epoch 10/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5000 - loss: 0.6678
Epoch 11/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - accuracy: 0.7500 - loss: 0.6663
Epoch 12/275
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.7500 - los

In [ ]:
model_multilayer_tanh.evaluate(input_test,label_xor)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - accuracy: 0.5000 - loss: 1.6102


[1.6101855039596558, 0.5]

In [ ]:
model_multilayer_tanh.predict(input_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step


array([[0.04250982],
       [0.9589113 ],
       [0.02462196],
       [0.92943555]], dtype=float32)